<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns="http://www.w3.org/1999/xhtml"
		xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
		version="1.0">

  <xsl:output method="text" encoding="UTF-8" media-type="text/plain" />

  <!-- end of the boilerplate -->
  <xsl:variable name="hipsu">'</xsl:variable>
  
  <xsl:template match="/">
    <xsl:variable name="rawlist" select="//select[@name='PREFIX']/option/@value"/>
    <xsl:variable name="nonempty" select="$rawlist[not(.='')]"/>

    <xsl:text>/**&#10;</xsl:text>
    <xsl:text> * Automatically generated by generate_prefixes.sh.&#10;</xsl:text>
    <xsl:text> * Edit the script, not this file!&#10;</xsl:text>
    <xsl:text> */&#10;&#10;</xsl:text>
    
    <xsl:text>$prefixes = array(&#10;</xsl:text>
    <xsl:for-each select="$nonempty">
      <xsl:sort select="string-length(.)" data-type="number" order="descending"/>
      <xsl:sort select="." order="ascending"/>
      <xsl:value-of select="concat('  &#34;',.,'&#34;')" />
      <xsl:choose>
	<xsl:when test="not(position()=last())">,&#10;</xsl:when>
	<xsl:otherwise>);&#10;</xsl:otherwise>
      </xsl:choose>
    </xsl:for-each>

    <xsl:text>$max_length = </xsl:text>
    <xsl:value-of select="//input[@name='NUMBER']/@maxlength"/>
    <xsl:text>;&#10;</xsl:text>

  </xsl:template>
</xsl:stylesheet>
